# Generated by Django 5.1.4 on 2025-01-03 16:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=200)),
                ('certificate', models.FileField(null=True, upload_to='certifications/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])])),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
