# Generated by Django 5.1.4 on 2025-01-04 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_email', models.EmailField(max_length=254)),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.department')),
                ('developers', models.ManyToManyField(limit_choices_to={'user__user_type': 3}, related_name='projects_developed', to='myapp.registration')),
                ('team_leader', models.ForeignKey(blank=True, limit_choices_to={'user__user_type': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to='myapp.registration')),
            ],
        ),
    ]
