# Generated by Django 5.1.4 on 2025-01-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_task_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_update',
            field=models.TextField(blank=True, null=True),
        ),
    ]
