# Generated by Django 5.1.4 on 2025-01-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_task_team_leader_comments_task_team_leader_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='team_leader_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], default='Pending', max_length=20),
        ),
    ]
