# Generated by Django 5.1.4 on 2025-01-07 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_task_team_leader_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskProgressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_update', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_history', to='myapp.task')),
            ],
        ),
    ]
