# Generated by Django 5.1.4 on 2025-01-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_taskupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
