# Generated by Django 5.1.4 on 2025-01-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_registration_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='team_leader',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__user_type': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developers', to='myapp.registration'),
        ),
    ]
