# Generated by Django 5.1.4 on 2025-01-10 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_registration_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskupdate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='progress_update',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
