# Generated by Django 5.1.4 on 2025-01-10 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_taskupdate_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupdate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
