# Generated by Django 5.1.4 on 2025-01-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_taskupdate_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
