# Generated by Django 5.1.4 on 2025-01-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_taskupdate_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
