# Generated by Django 5.1.4 on 2025-01-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_projectupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskupdate',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
